"""Unit test — no DB, no real network, per Architecture.md's tests/unit/ scope.

Real, live-found gap (2026-10-05 fidelity audit): a script the user already approved on a prior
turn ("turn this into a video") used to be silently regenerated by Script Writer inside
`narrative_lead`, producing a different script than the one actually shown/approved. Verifies
`brief["approved_script"]` is reused verbatim and `script_writer` is never called in that case."""
from unittest.mock import AsyncMock, patch

import pytest

from src.services.leads.narrative_lead import run_narrative_lead
from src.services.specialists.runner import AgenticStepResult


def _shot_planner_result() -> AgenticStepResult:
    return AgenticStepResult(
        specialist_name="shot_planner",
        model="fake-model",
        data={"shots": ["Shot 1: wide establishing shot"], "overall_story": "unboxing story"},
        tool_calls=[],
    )


def _pacing_result() -> AgenticStepResult:
    return AgenticStepResult(
        specialist_name="pacing_editor", model="fake-model", data={"pacing_target": "moderate"}, tool_calls=[],
    )


@pytest.mark.asyncio
async def test_reuses_approved_script_without_calling_script_writer() -> None:
    brief = {"approved_script": "Hey everyone, let's unbox this phone!"}

    async def _fake_agentic(specialist_name: str, **kwargs):
        assert specialist_name != "script_writer", "approved_script must bypass script_writer entirely"
        if specialist_name == "shot_planner":
            return _shot_planner_result()
        if specialist_name == "pacing_editor":
            return _pacing_result()
        raise AssertionError(f"unexpected specialist call: {specialist_name}")

    with patch("src.services.leads.narrative_lead.run_specialist_agentic", new=AsyncMock(side_effect=_fake_agentic)):
        plan = await run_narrative_lead(brief=brief, user_message="make a 10 second unboxing video")

    assert plan.script_line == "Hey everyone, let's unbox this phone!"
