"""
Repository protocols — the local -> online swap point (Architecture.md section 4).

Services depend on these Protocols, never on a concrete SQLite class (Dependency Inversion,
Rules.md section 1). Swapping to Postgres/Supabase later means writing one new class per protocol
that satisfies the same shape — zero changes to any service.
"""
from __future__ import annotations

from typing import Protocol

from ..models.brand_profile import BrandProfileModel
from ..models.canvas_element import CanvasElementModel
from ..models.canvas_element_version import CanvasElementVersionModel
from ..models.generation_job import GenerationJobModel
from ..models.product_profile import ProductProfileModel
from ..models.session import SessionModel
from ..models.tool_call_log import ToolCallLogModel


class SessionRepository(Protocol):
    async def add(self, session: SessionModel) -> SessionModel: ...
    async def get(self, session_id: str) -> SessionModel | None: ...
    async def update(self, session: SessionModel) -> SessionModel: ...


class CanvasRepository(Protocol):
    async def add_element(self, element: CanvasElementModel) -> CanvasElementModel: ...
    async def get_element(self, element_id: str) -> CanvasElementModel | None: ...
    async def list_for_session(self, session_id: str) -> list[CanvasElementModel]: ...
    async def update_element(self, element: CanvasElementModel) -> CanvasElementModel: ...


class CanvasVersionRepository(Protocol):
    async def add(self, version: CanvasElementVersionModel) -> CanvasElementVersionModel: ...
    async def list_for_element(self, element_id: str) -> list[CanvasElementVersionModel]: ...
    async def delete_versions_after(self, element_id: str, version: int) -> None: ...


class BrandRepository(Protocol):
    async def add(self, brand: BrandProfileModel) -> BrandProfileModel: ...
    async def get(self, brand_id: str) -> BrandProfileModel | None: ...
    async def list_all(self) -> list[BrandProfileModel]: ...


class ProductRepository(Protocol):
    async def add(self, product: ProductProfileModel) -> ProductProfileModel: ...
    async def get(self, product_id: str) -> ProductProfileModel | None: ...
    async def list_all(self) -> list[ProductProfileModel]: ...


class GenerationJobRepository(Protocol):
    async def add(self, job: GenerationJobModel) -> GenerationJobModel: ...
    async def get(self, job_id: str) -> GenerationJobModel | None: ...
    async def update(self, job: GenerationJobModel) -> GenerationJobModel: ...


class ToolCallLogRepository(Protocol):
    async def add(self, log: ToolCallLogModel) -> ToolCallLogModel: ...
    async def list_for_session(self, session_id: str) -> list[ToolCallLogModel]: ...
