"""
Motion Lead — Architecture.md section 1a: Camera Director -> Video Editor/Cutter -> Sound
Designer -> Overlay Artist. Runs last in the full-video pipeline (Narrative Lead -> Scene Lead ->
Motion Lead), consuming the NarrativePlan and the ScenePlan's already-generated scene image.

Camera Director no longer generates its own starting frame — Scene Lead's Environment Designer
already produced it (Memory.md, Phase 2 correction, matching the reference architecture's own
tool-ownership table). Camera Director's only job now is deciding the motion and genuinely
choosing to call base_video_generator on that existing image; Video Editor/Cutter genuinely
decides whether/how to call video_stitcher, rather than this file calling it unconditionally.

Sound Designer now has a real `text_to_speech` tool (local Kokoro-82M, no external cost) — when it
genuinely calls it for a voiceover, the result is a real audio asset, surfaced as its own
`audio_storage_ref`. Sound Designer ALSO has `mux_audio_into_video`, but this executor never calls
it itself and never muxes automatically just because both a video and an audio track exist — per
the user's explicit instruction, muxing is the specialist's own genuine, optional decision (see
`sound_designer.md`). Only when Sound Designer chooses to call it does this file's final
`storage_ref` become the muxed result (`audio_muxed_into_video: true`); otherwise the plain
stitched video and the separate audio asset both stay exactly as produced. Overlay Artist also has
a real `text_overlay` tool (Memory.md, Phase 3) — when it genuinely calls it, the result is a new
overlaid STILL IMAGE (drawn on the source frame, before animation), not a modified version of the
final video's own pixels, so it's surfaced as its own `overlay_image_storage_ref` rather than
replacing the video's `storage_ref` (Rules.md section 2: no silently defaulting a real result to a
fake "not applied").
"""
from __future__ import annotations

import asyncio
import json

from ...core.exceptions import SpecialistFailed
from ...core.middleware.logging import get_logger
from ..specialists.runner import run_specialist_agentic
from .base import LeadResult, LeadSpec, NarrativePlan, ScenePlan

log = get_logger(__name__)

MOTION_LEAD = LeadSpec(
    name="motion_lead",
    specialist_sequence=("camera_director", "video_editor_cutter", "sound_designer", "overlay_artist"),
    full_job_trigger="New finished video",
)


async def run_motion_lead(
    *, brief: dict, narrative: NarrativePlan | None = None, scene: ScenePlan | None = None
) -> LeadResult:
    """Runs the full 4-specialist sequence for one new video clip. Returns a LeadResult with the
    final storage_ref, or raises SpecialistFailed if a step couldn't produce a usable result.
    """
    idea = brief.get("idea") or brief.get("initial_message") or ""
    primary_shot = narrative.shots[0] if narrative and narrative.shots else idea

    if not scene or not scene.scene_image_storage_ref:
        raise SpecialistFailed(
            "camera_director", "no scene image available to animate — Scene Lead must run first"
        )

    context_parts = [
        f"Shot to produce:\n{primary_shot}",
        f"Source image storage_ref (already generated by Scene Lead — animate THIS, do not "
        f"generate a new starting image yourself): {scene.scene_image_storage_ref}",
    ]
    if narrative:
        context_parts.append(f"Overall story:\n{narrative.overall_story}")
        if narrative.script_line:
            context_parts.append(f"Script line to accompany this shot:\n{narrative.script_line}")
        context_parts.append(f"Pacing target:\n{narrative.pacing_target}")
    context_parts.append(f"Environment:\n{scene.environment_description}")
    if scene.prop_description:
        context_parts.append(f"Props:\n{scene.prop_description}")
    context_parts.append(f"Lighting:\n{scene.lighting_description}")
    context_parts.append(f"Full brief:\n{json.dumps(brief)}")

    camera = await run_specialist_agentic("camera_director", context="\n\n".join(context_parts))
    video_call = camera.latest_call("base_video_generator")
    if not video_call or not video_call.data.get("storage_ref"):
        raise SpecialistFailed("camera_director", "did not produce a video via base_video_generator")
    raw_clip_storage_ref = video_call.data["storage_ref"]
    motion_prompt = camera.get("motion_prompt", "")
    # The real aspect_ratio actually sent to base_video_generator, not the LLM's own restated
    # JSON field — what Format/Technical QA's compliance check verifies the output against.
    aspect_ratio = video_call.args.get("aspect_ratio", "16:9")

    editor = await run_specialist_agentic(
        "video_editor_cutter",
        context=f"Raw clip storage_ref: {raw_clip_storage_ref}\nMotion prompt used:\n{motion_prompt}",
    )
    stitch_result = editor.latest_result("video_stitcher")
    if stitch_result and stitch_result.get("storage_ref"):
        storage_ref = stitch_result["storage_ref"]
        stitched = True
    else:
        # Video Editor/Cutter genuinely chose not to call video_stitcher (or it failed) — the raw
        # clip is still a valid result, reflected honestly rather than forced.
        log.warning("motion_lead_no_stitch", extra={"_extra_specialist": "video_editor_cutter"})
        storage_ref = raw_clip_storage_ref
        stitched = False

    # Sound Designer and Overlay Artist depend only on the idea/motion_prompt already decided
    # above, not on each other's output — genuinely independent, run concurrently
    # (Architecture.md's own example: parallelize specialists with no dependency between them).
    sound, overlay = await asyncio.gather(
        run_specialist_agentic(
            "sound_designer",
            context=(
                f"Campaign idea:\n{idea}\n\nMotion prompt:\n{motion_prompt}\n\n"
                f"video_storage_ref (the finished clip, if you decide a voiceover belongs muxed "
                f"into it): {storage_ref}"
            ),
        ),
        run_specialist_agentic(
            "overlay_artist",
            context=(
                f"Campaign idea:\n{idea}\n\n"
                f"source_frame_storage_ref (the still image, before animation — text_overlay only "
                f"works on this, not on the finished video): {scene.scene_image_storage_ref}"
            ),
        ),
    )

    sound_call = sound.latest_call("text_to_speech")
    audio_storage_ref = sound_call.data.get("storage_ref") if sound_call and sound_call.ok else None

    # Muxing is the specialist's own genuine decision (see sound_designer.md) — not something this
    # executor does automatically just because both a video and an audio track exist.
    mux_call = sound.latest_call("mux_audio_into_video")
    audio_muxed_into_video = bool(mux_call and mux_call.ok and mux_call.data.get("storage_ref"))
    if audio_muxed_into_video:
        storage_ref = mux_call.data["storage_ref"]

    overlay_call = overlay.latest_call("text_overlay")
    overlay_image_storage_ref = overlay_call.data.get("storage_ref") if overlay_call and overlay_call.ok else None

    all_steps = (camera, editor, sound, overlay)
    return LeadResult(
        storage_ref=storage_ref,
        produced_by_specialist="camera_director",
        element_type="video",
        metadata={
            "primary_shot": primary_shot,
            "shot_count_proposed": len(narrative.shots) if narrative else 1,
            "motion_prompt": motion_prompt,
            "aspect_ratio": aspect_ratio,
            "source_frame_storage_ref": scene.scene_image_storage_ref,
            "raw_clip_storage_ref": raw_clip_storage_ref,
            "pacing_note": editor.get("pacing_note", ""),
            "stitched": stitched,
            "audio_recommendation": sound.get("audio_recommendation", ""),
            "audio_notes": sound.get("notes", ""),
            "audio_applied": audio_storage_ref is not None,
            "audio_storage_ref": audio_storage_ref,
            "audio_muxed_into_video": audio_muxed_into_video,
            "overlay_recommendation": overlay.data if overlay.get("needs_overlay") else None,
            "overlay_applied": overlay_image_storage_ref is not None,
            "overlay_image_storage_ref": overlay_image_storage_ref,
            "tool_calls_made": [
                {"specialist": step.specialist_name, "tool": call.tool_name, "ok": call.ok}
                for step in all_steps
                for call in step.tool_calls
            ],
        },
    )
